package com.osrapi.models.dwarfstar.barbarianprince;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author drau
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "programmed_event_rule_lookup",
schema = "dwarfstar_barbarian_prince")
public final class EventOptionRuleEntity {
	/** the event id. */
	@NotNull
	@Column(name = "programmed_event_id")
	@JsonProperty("programmed_event_id")
	private long				eventId;
	/** the event option. */
	@OneToOne(cascade = CascadeType.ALL, targetEntity = EventOptionEntity.class,
			fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "event_option_id",
	referencedColumnName = "event_option_id")
	private EventOptionEntity	option;
	/** the event option. */
	@OneToOne(cascade = CascadeType.ALL, targetEntity = EventRuleEntity.class,
			fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "event_rule_id", referencedColumnName = "event_rule_id")
	private EventRuleEntity		rule;
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "programmed_event_rule_lookup_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long				id;
	/** Creates a new instance of {@link EventOptionRuleEntity}. */
	public EventOptionRuleEntity() {
		super();
	}
	/**
	 * Gets the event id.
	 * @return {@link long}
	 */
	public long getEventId() {
		return eventId;
	}
	/**
	 * Gets the event option.
	 * @return {@link EventOptionEntity}
	 */
	public EventOptionEntity getOption() {
		return option;
	}
	/**
	 * Gets the event rule.
	 * @return {@link EventRuleEntity}
	 */
	public EventRuleEntity getRule() {
		return rule;
	}
	/**
	 * Gets the id.
	 * @return {@link long}
	 */
	public long getId() {
		return id;
	}
	/**
	 * Sets the event id.
	 * @param val the new value
	 */
	public void setEventId(final long val) {
		eventId = val;
	}
	/**
	 * Sets the event option.
	 * @param val the event option to set
	 */
	public void setOption(final EventOptionEntity val) {
		option = val;
	}
	/**
	 * Sets the event rule.
	 * @param val the event rule to set
	 */
	public void setRule(final EventRuleEntity val) {
		rule = val;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final long val) {
		id = val;
	}
}
