package com.osrapi.models.dwarfstar.barbarianprince;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * 
 * @author drau
 *
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "random_event_outcome",
schema = "dwarfstar_barbarian_prince")
public final class RandomOutcomeEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
    @Column(name = "random_event_outcome_id")
	@JsonIgnore
    private long     id;
	/** the die roll assigned to this outcome. */
    @Column(name = "die_roll")
    private long     roll;
    /** the outcome.  possibly a rule or another event. */
    @Column(name = "outcome")
    private long     outcome; 
	/** Creates a new instance of {@link RandomOutcomeEntity}. */
	public RandomOutcomeEntity() {
		super();
	}
	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}
	/**
	 * Creates a new instance of {@link RandomOutcomeEntity}.
	 * @param i the id
	 * @param r the die roll assigned to this outcome
	 * @param o the outcome
	 */
	public RandomOutcomeEntity(final long i, final long r, final long o) {
		id = i;
		roll = r;
		outcome = o;
	}
	/**
	 * @return the roll
	 */
	public long getRoll() {
		return roll;
	}
	/**
	 * @return the outcome
	 */
	public long getOutcome() {
		return outcome;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final long val) {
		id = val;
	}
	/**
	 * Sets the outcome.
	 * @param val the new value
	 */
	public void setOutcome(final long val) {
		outcome = val;
	}
	/**
	 * Sets the roll.
	 * @param val the new value
	 */
	public void setRoll(final long val) {
		roll = val;
	}
}
