package com.osrapi.models.dwarfstar.barbarianprince;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * 
 * @author drau
 *
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "game_text", schema = "dwarfstar_barbarian_prince")
public final class TextEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "game_text_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	/** the text section. */
	@Column(name = "section_id")
	@NotNull
	private String section;
	/** the text. */
	@Column(name = "section_text")
	@NotNull
	private String text;
	/** Creates a new instance of {@link TextEntity}. */
	public TextEntity() {
		super();
	}
	/**
	 * Gets the id.
	 * @return {@link long}
	 */
	public long getId() {
		return id;
	}
	/**
	 * Gets the section.
	 * @return {@link String}
	 */
	public String getSection() {
		return section;
	}
	/**
	 * Gets the text.
	 * @return {@link String}
	 */
	public String getText() {
		return text;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final long val) {
		id = val;
	}
	/**
	 * Sets the section.
	 * @param val the new value
	 */
	public void setSection(final String val) {
		section = val;
	}
	/**
	 * Sets the text.
	 * @param val the new value
	 */
	public void setText(final String val) {
		text = val;
	}
}
