package com.osrapi.models.wfrp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * 
 * @author drau
 *
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "race",
schema = "wfrp")
public final class WFRPRaceEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
    @Column(name = "race_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
    private long     id;
	/** the background. */
    private String     background;
	/** the description. */
    private String     description;
	/** the name. */
    private String     name;
	/** Creates a new instance of {@link WFRPRaceEntity}. */
	public WFRPRaceEntity() {
		super();
	}
	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}
	/**
	 * Creates a new instance of {@link WFRPRaceEntity}.
	 * @param i the id
	 * @param n the name
	 */
	public WFRPRaceEntity(final long i, final String n) {
		id = i;
		name = n;
	}
	/**
	 * Gets the background.
	 * @return {@link String}
	 */
	public String getBackground() {
		return background;
	}
	/**
	 * Gets the description.
	 * @return {@link String}
	 */
	public String getDescription() {
		return description;
	}
	/**
	 * Gets the name.
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final long val) {
		id = val;
	}
	/**
	 * Sets the background.
	 * @param val the new value
	 */
	public void setBackground(final String val) {
		background = val;
	}
	/**
	 * Sets the description.
	 * @param val the new value
	 */
	public void setDescription(final String val) {
		description = val;
	}
	/**
	 * Sets the name.
	 * @param val the new value
	 */
	public void setName(final String val) {
		name = val;
	}
}
