package com.osrapi.models;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * 
 * @author drau
 *
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "event", schema = "dwarfstar_barbarian_prince")
public final class EventEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "event_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	/** the sub event name. */
	@NotNull
	private String name;
	/** the list of sub-events making up this event. */
    @OneToMany(targetEntity = SubEventEntity.class, fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(name = "programmed_event_lookup",
    schema = "dwarfstar_barbarian_prince", 
    joinColumns = @JoinColumn(name = "event_id",
    referencedColumnName = "event_id"),
    inverseJoinColumns = @JoinColumn(name = "programmed_event_id", 
    referencedColumnName = "programmed_event_id")) 
	private List<SubEventEntity> subevents;
	/** Creates a new instance of {@link EventEntity}. */
	public EventEntity() {
		super();
	}
	/**
	 * Creates a new instance of {@link EventEntity}.
	 * @param n the name
	 */
	public EventEntity(final String n) {
		name = n;
	}
	/**
	 * Gets the id.
	 * @return {@link long}
	 */
	public long getId() {
		return id;
	}
	/**
	 * Gets the name.
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}
	/**
	 * Gets the list of sub-events.
	 * @return {@link List}<{@link SubEventEntity}>
	 */
	public List<SubEventEntity> getSubevents() {
		return subevents;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final long val) {
		id = val;
	}
	/**
	 * Sets the name.
	 * @param val the new value
	 */
	public void setName(final String val) {
		name = val;
	}
	/**
	 * Sets the list of sub-events.
	 * @param list the list to set
	 */
	public void setSubevents(final List<SubEventEntity> list) {
		subevents = list;
	}
}
