package com.osrapi.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * 
 * @author drau
 *
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "hex_feature", schema = "dwarfstar_barbarian_prince")
public final class HexFeatureEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
	@Column(name = "hex_feature_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	/** the sub event name. */
	@NotNull
	private String name;
	/** Creates a new instance of {@link HexFeatureEntity}. */
	public HexFeatureEntity() {
		super();
	}
	/**
	 * Creates a new instance of {@link HexFeatureEntity}.
	 * @param n the name
	 */
	public HexFeatureEntity(final String n) {
		name = n;
	}
	/**
	 * Gets the feature's bit flag.
	 * @return {@link long}
	 */
	public long getFlag() {
		return (long) Math.pow(2, id);
	}
	/**
	 * Gets the id.
	 * @return {@link long}
	 */
	public long getId() {
		return id;
	}
	/**
	 * Gets the name.
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final long val) {
		id = val;
	}
	/**
	 * Sets the name.
	 * @param val the new value
	 */
	public void setName(final String val) {
		name = val;
	}
}
