package com.osrapi.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * 
 * @author drau
 *
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Entity
@Table(name = "turn_phase",
schema = "dwarfstar_barbarian_prince")
public final class TurnPhaseEntity {
	/**
	 * the primary key - an autogenerated id (unique for each user in the db).
	 */
	@Id
    @Column(name = "turn_phase_id")
    private long     id;
	/** the name. */
    private String     name;
	/** Creates a new instance of {@link TurnPhaseEntity}. */
	public TurnPhaseEntity() {
		super();
	}
	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}
	/**
	 * Creates a new instance of {@link TurnPhaseEntity}.
	 * @param i the id
	 * @param n the name
	 */
	public TurnPhaseEntity(final long i, final String n) {
		id = i;
		name = n;
	}
	/**
	 * Gets the name.
	 * @return {@link String}
	 */
	public String getName() {
		return name;
	}
	/**
	 * Sets the id.
	 * @param val the new value
	 */
	public void setId(final long val) {
		id = val;
	}
	/**
	 * Sets the name.
	 * @param val the new value
	 */
	public void setName(final String val) {
		name = val;
	}
}
